global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

      
  - job_name: 'kuai_admin'
    static_configs:
      - targets: ['ip:9100']  # 根据实际情况设置
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ip'
        
  - job_name: 'kuai_sql'
    static_configs:
      - targets: ['ip:9100']  # 根据实际情况设置
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ip'       
        
  - job_name: 'nginx'
    static_configs:
      - targets: ['ip:9113']
